export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SAVE_USER_DOCUMENT_SUCCESS = 'SAVE_USER_DOCUMENT_SUCCESS';
export const GET_USER_DOCUMENT_SUCCESS = 'GET_USER_DOCUMENT_SUCCESS';
export const GET_CURRENT_USER_DOCUMENT_SUCCESS =
  'GET_CURRENT_USER_DOCUMENT_SUCCESS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const SEARCH_DOCUMENTS = 'SEARCH_DOCUMENTS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const SAVE_DOCUMENT = 'SAVE_DOCUMENT';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

